#!/bin/sh

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
##############################################################################

# Resolve links: $0 may be a link
app_path=$0
while [ -h "$app_path" ]; do
    ls_output=$(ls -ld "$app_path")
    link_target=$(echo "$ls_output" | sed 's/.* -> //')
    case $link_target in
        /*) app_path=$link_target ;;
        *) app_path=$(dirname "$app_path")/$link_target ;;
    esac
done
APP_HOME=$(cd "$(dirname "$app_path")" && pwd -P) || exit

# Add default JVM options here
DEFAULT_JVM_OPTS="-Xmx128m -Xms64m"

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use
if [ -n "$JAVA_HOME" ]; then
    JAVACMD=$JAVA_HOME/bin/java
else
    JAVACMD=java
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain "$@"
